/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agendamento`; params?: Router.UnknownInputParams; } | { pathname: `/historico`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recuperarSenha`; params?: Router.UnknownInputParams; } | { pathname: `/registrar`; params?: Router.UnknownInputParams; } | { pathname: `/telaUsuario`; params?: Router.UnknownInputParams; } | { pathname: `/teste`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/barbeiros`; params?: Router.UnknownInputParams; } | { pathname: `/admin/confirmAgendamentos`; params?: Router.UnknownInputParams; } | { pathname: `/admin/perfilAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/servicos`; params?: Router.UnknownInputParams; } | { pathname: `/admin/TelaAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/agendamento`; params?: Router.UnknownOutputParams; } | { pathname: `/historico`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/recuperarSenha`; params?: Router.UnknownOutputParams; } | { pathname: `/registrar`; params?: Router.UnknownOutputParams; } | { pathname: `/telaUsuario`; params?: Router.UnknownOutputParams; } | { pathname: `/teste`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/barbeiros`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/confirmAgendamentos`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/perfilAdmin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/servicos`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/TelaAdmin`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/agendamento${`?${string}` | `#${string}` | ''}` | `/historico${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/recuperarSenha${`?${string}` | `#${string}` | ''}` | `/registrar${`?${string}` | `#${string}` | ''}` | `/telaUsuario${`?${string}` | `#${string}` | ''}` | `/teste${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/barbeiros${`?${string}` | `#${string}` | ''}` | `/admin/confirmAgendamentos${`?${string}` | `#${string}` | ''}` | `/admin/perfilAdmin${`?${string}` | `#${string}` | ''}` | `/admin/servicos${`?${string}` | `#${string}` | ''}` | `/admin/TelaAdmin${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/agendamento`; params?: Router.UnknownInputParams; } | { pathname: `/historico`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recuperarSenha`; params?: Router.UnknownInputParams; } | { pathname: `/registrar`; params?: Router.UnknownInputParams; } | { pathname: `/telaUsuario`; params?: Router.UnknownInputParams; } | { pathname: `/teste`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/barbeiros`; params?: Router.UnknownInputParams; } | { pathname: `/admin/confirmAgendamentos`; params?: Router.UnknownInputParams; } | { pathname: `/admin/perfilAdmin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/servicos`; params?: Router.UnknownInputParams; } | { pathname: `/admin/TelaAdmin`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
